mainGuild = ""

songChallengeChannel = ""

genreHubChannel = ""

[statisticChannels]
users = ""
plusUsers = ""
streams =  ""
tracks = ""
artists = ""
albums = ""

[statsfmConfig]
baseUrl = ""
acccessToken = "" # Nullable!

[status]
apiUrl = ""
apiAuth = ""

[roles]
beta = ""
plus = ""
ios = ""
android = ""
